#!/system/bin/sh

chown 0:0 /system/xbin/su
chmod 6755 /system/xbin/su

# Fix VPN
rm -r /data/misc/vpn
ln -s /data/data/misc/vpn /data/misc/

# Tweak drives for better speed

BML=`ls -d /sys/block/bml*`;
MMC=`ls -d /sys/block/mmc*`;
STL=`ls -d /sys/block/stl*`;

READ_AHEAD_KB="384";
NR_REQUESTS="128";
for i in $STL;
do
	echo $NR_REQUESTS > $i/queue/nr_requests;
	echo $READ_AHEAD_KB > $i/queue/read_ahead_kb;
	echo 0 > $i/queue/rotational;
	echo 1 > $i/queue/iosched/fifo_batch;
done;

READ_AHEAD_KB="384";
NR_REQUESTS="128";
for i in $MMC;
do
	echo $NR_REQUESTS > $i/queue/nr_requests;
	echo $READ_AHEAD_KB > $i/queue/read_ahead_kb;
	echo 0 > $i/queue/rotational;
	echo 1 > $i/queue/iosched/fifo_batch;
done;
