USE_CAMERA_STUB := true


# inherit from the proprietary version
-include vendor/samsung/callisto/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7k
TARGET_CPU_ABI := armeabi
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_BOARD_PLATFORM := msm7k
#Kernel
TARGET_NO_RECOVERY := true
TARGET_NO_KERNEL := true




#WIFI
WIFI_DRIVER_MODULE_NAME     := ar6000
WIFI_DRIVER_MODULE_PATH     := rfkill
BOARD_WPA_SUPPLICANT_DRIVER := WEXT




#Audio 
HAVE_HTC_AUDIO_DRIVER := true
BOARD_USES_GENERIC_AUDIO := true

#Bluetooth

BOARD_HAVE_BLUETOOTH := true
BT_ALT_STACK := true
BRCM_BT_USE_BTL_IF := true
BRCM_BTL_INCLUDE_A2DP := true
BRCM_BTL_INCLUDE_OBEX := true
BRCM_BTL_OBEX_USE_DBUS := true

# GPU
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200



# Radio FM
TARGET_PROVIDES_LIBAUDIO := true 

BOARD_HAVE_FM_RADIO := true
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO
BOARD_FM_DEVICE := si4708
#BOARD_USE_BROADCOM_FM_VOLUME_HACK := true


# Screencap to capture frame buffer for ddms
BOARD_USE_SCREENCAP := true

# USB
BOARD_USE_USB_MASS_STORAGE_SWITCH := true

# fix this up by examining /proc/mtd on a running device
#BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00380000
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00480000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x08c60000
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
#BOARD_FLASH_BLOCK_SIZE := 131072

#TARGET_PREBUILT_KERNEL := device/samsung/callisto/kernel

#BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_BOOT_DEVICE := /dev/block/bml9

BOARD_DATA_DEVICE := /dev/block/stl13
BOARD_DATA_FILESYSTEM := ext4
BOARD_SYSTEM_DEVICE := /dev/block/stl12
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_CACHE_DEVICE := /dev/block/stl14
BOARD_CACHE_FILESYSTEM := ext4
BOARD_SDCARD_DEVICE_SECONDARY := NULL
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_RECOVERY_DEVICE := /dev/block/bml10
BOARD_LDPI_RECOVERY := true
